/* IRON FIST — Nivel 3 */
(() => {
"use strict";
const $=id=>document.getElementById(id),play=id=>{$(id)?.play().catch(()=>{})},pause=id=>{$(id)?.pause()};
const ids=["Meteoritolvl3","Meteorito2lvl3","Meteorito3lvl3","Meteorito4lvl3"];
let s={tiempo:50,puntos:0,jugando:false,pausado:false,terminado:false,timer:null,impact:null};
function hud(){if($("Tiempolvl3"))$("Tiempolvl3").textContent=s.tiempo;if($("Puntajelvl3"))$("Puntajelvl3").textContent=s.puntos+" / 40";const p=$("Puntajelvl3")?.parentElement?.querySelector(".ProgresoInternoLvl3");if(p)p.style.width=(s.puntos/40*100)+"%";}
function barra(){const box=$("Puntajelvl3");if(box&&!box.querySelector(".BarraProgresoLvl3")){const b=document.createElement("div");b.className="BarraProgresoLvl3";b.innerHTML='<div class="ProgresoInternoLvl3"></div>';box.style.position="relative";box.appendChild(b);}}
function ocultar(e){if(e){e.style.transition="none";e.style.left="-15%";e.dataset.tocado="0";}}
function mover(e){if(!e||!s.jugando||s.pausado)return;e.dataset.tocado="0";e.style.transition="left 1.65s linear,top .15s linear";e.style.top=Math.max(5,Math.random()*85)+"%";e.style.left="82%";}
function detener(){ids.forEach(id=>{const e=$(id);if(e){clearInterval(Number(e.dataset.timer));e.dataset.timer="";}});}
function iniciarMeteoritos(){ids.forEach((id,i)=>{const e=$(id);if(!e)return;ocultar(e);setTimeout(()=>mover(e),550+i*300);e.dataset.timer=setInterval(()=>mover(e),1650+i*200);});}
function reiniciar(m){s.tiempo=50;s.puntos=0;hud();ids.forEach(id=>ocultar($(id)));play("Perdiste_sound");if(window.Swal)Swal.fire({title:"¡Defensa fallida!",text:m+" La ronda se reiniciará.",icon:"warning",confirmButtonText:"Continuar",background:"#07101c",color:"#fff"});setTimeout(()=>{if(s.jugando&&!s.terminado)iniciarMeteoritos();},700);}
function victoria(){s.terminado=true;s.jugando=false;clearInterval(s.timer);clearInterval(s.impact);detener();ids.forEach(id=>ocultar($(id)));pause("Fondo_Ciberpunk");play("Triunfo");play("Musica_Final");$("Pantalla_Ovnislvl3").style.display="flex";$("Pantalla_Nodrizalvl3").style.display="flex";$("Pantalla_Ovnis2lvl3").style.display="flex";$("Pantalla_creditoslvl3").style.display="block";$("Creditoslvl3").style.display="block";$("Proximolvl3").style.display="block";if(window.Swal)Swal.fire({title:"¡MISIÓN COMPLETADA!",html:"Has destruido los <b>40 meteoritos</b> del Nivel 3.<br><br>La defensa del planeta ha sido completada.",icon:"success",confirmButtonText:"Excelente",background:"#07101c",color:"#fff"});}
function golpe(id){if(!s.jugando||s.pausado||s.terminado)return;const e=$(id);if(!e||e.dataset.tocado==="1")return;e.dataset.tocado="1";s.puntos++;hud();play(id===ids[0]?"Puntos_sound":id===ids[1]?"Punto2":id===ids[2]?"Punto3":"Punto4");e.classList.add("impactoMeteorito");ocultar(e);if(s.puntos>=40)victoria();}
function iniciar(){s={tiempo:50,puntos:0,jugando:true,pausado:false,terminado:false,timer:null,impact:null};hud();$("Startlvl3").style.display="none";$("Pausa_Pantallalvl3").style.display="none";$("Pantalla_Ovnislvl3").style.display="none";$("Pantalla_Nodrizalvl3").style.display="none";$("Pantalla_Ovnis2lvl3").style.display="none";$("Pantalla_creditoslvl3").style.display="none";$("Creditoslvl3").style.display="none";$("Proximolvl3").style.display="none";play("Fondo_Ciberpunk");iniciarMeteoritos();s.timer=setInterval(()=>{if(!s.pausado&&s.jugando){s.tiempo--;hud();if(s.tiempo<=0)reiniciar("Se agotó el tiempo.")}},1000);s.impact=setInterval(()=>{const a=$("NIVEL3")?.querySelector(".Contenedorlvl3");if(!a||s.pausado)return;const limite=a.getBoundingClientRect().right*.78;ids.forEach(id=>{const e=$(id);if(e&&e.getBoundingClientRect().left>=limite)reiniciar("Un meteorito alcanzó la zona de impacto.");});},120);}
function pausa(){if(!s.jugando||s.terminado)return;s.pausado=!s.pausado;$("Pausa_Pantallalvl3").style.display=s.pausado?"flex":"none";if(s.pausado)pause("Fondo_Ciberpunk");else play("Fondo_Ciberpunk");}
function cuenta(){const box=$("Contenedor_contadorlvl3"),sp=$("RGBlvl3");let n=3;box.style.display="block";sp.textContent=n;const t=setInterval(()=>{n--;sp.textContent=n>0?n:"¡YA!";if(n<=0){clearInterval(t);setTimeout(()=>{box.style.display="none";iniciar();},350);}},800);}
window.prepararNivel3=()=>{s={tiempo:50,puntos:0,jugando:false,pausado:false,terminado:false,timer:null,impact:null};hud();$("Startlvl3").style.display="flex";$("Pausa_Pantallalvl3").style.display="none";$("Pantalla_Ovnislvl3").style.display="none";$("Pantalla_Nodrizalvl3").style.display="none";$("Pantalla_Ovnis2lvl3").style.display="none";$("Pantalla_creditoslvl3").style.display="none";$("Creditoslvl3").style.display="none";$("Proximolvl3").style.display="none";ids.forEach(id=>ocultar($(id)));};
document.addEventListener("DOMContentLoaded",()=>{barra();hud();ids.forEach(id=>$(id)?.addEventListener("pointerdown",()=>golpe(id)));$("Playlvl3")?.addEventListener("click",cuenta);$("Pauselvl3")?.addEventListener("click",pausa);});
})();